/*

 BRICK_WIDE_TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 2

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/
#pragma bank 255
#ifndef __INTELLISENSE__
const void __at(255) __bank_BRICK_WIDE_TILES;
#endif
/* Start of tile array. */
unsigned char BRICK_WIDE_TILES[] =
    {
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0xFF, 0xFF, 0x80, 0xFF, 0xAA, 0xD5, 0x95, 0xEA,
        0xAA, 0xD5, 0x95, 0xEA, 0xFF, 0xFF, 0xFF, 0xFF,
        0xFF, 0xFF, 0x03, 0xFF, 0xAB, 0x57, 0x57, 0xAB,
        0xAB, 0x57, 0x57, 0xAB, 0xFF, 0xFF, 0xFF, 0xFF};

/* End of BRICK_WIDE_TILES.C */
