/*

 BRICK_SMALL_COLLISION.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : basic_collisions.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BRICK_SMALL_COLLISIONWidth 20
#define BRICK_SMALL_COLLISIONHeight 18
#define BRICK_SMALL_COLLISIONBank 0

extern unsigned char BRICK_SMALL_COLLISION[];
extern const void __bank_BRICK_SMALL_COLLISION;

/* End of BRICK_SMALL_COLLISION.H */
