/*

 BRICK_WIDE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Bank of tiles. */
#define BRICK_WIDE_TILESBank 0
extern const void __bank_BRICK_WIDE_TILES;

/* Start of tile array. */
extern unsigned char BRICK_WIDE_TILES[];

/* End of BRICK_WIDE_TILES.H */
