/*

 BRICK_WIDE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BRICK_WIDE_TILE_DATABank 0
/* Start of tile array. */
extern unsigned char BRICK_WIDE_TILE_DATA[];

/* End of BRICK_WIDE_TILES.H */
