/*

 BRICK_WIDE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 18
   Tile set      : dk_large bricks.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BRICK_WIDE_MAPWidth 100
#define BRICK_WIDE_MAPHeight 18
#define BRICK_WIDE_MAPBank 0

extern unsigned char BRICK_WIDE_MAP[];

/* End of BRICK_WIDE_MAP.H */
