/*

 BRICK_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\c_code\TileMapBuilder\gb_Tile Designer\tile_sets\dk_large bricks.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BRICK_MAPWidth 20
#define BRICK_MAPHeight 18
#define BRICK_MAPBank 0

extern unsigned char BRICK_MAP[];

/* End of BRICK_MAP.H */
