/*

 BRICK_WIDE_COLLISION.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 18
   Tile set      : basic_collisions.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BRICK_WIDE_COLLISIONWidth 100
#define BRICK_WIDE_COLLISIONHeight 18
#define BRICK_WIDE_COLLISIONBank 0

extern unsigned char BRICK_WIDE_COLLISION[];

/* End of BRICK_WIDE_COLLISION.H */
