//AUTOGENERATED FILE FROM png2mtspr
#define bullet_TILE_H 16
#define bullet_WIDTH 8
#define bullet_HEIGHT 8
#define bullet_PIVOT_X 4
#define bullet_PIVOT_Y 4

extern const UINT8 bullet_data[32];
extern const metasprite_t* const bullet_metasprites[1];
