/*

 COLLISION_WIDE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 18
   Tile set      : basic_collisions.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define COLLISION_WIDE_MAPWidth 100
#define COLLISION_WIDE_MAPHeight 18
#define COLLISION_WIDE_MAPBank 0

extern unsigned char COLLISION_WIDE_MAP[];

/* End of COLLISION_WIDE_MAP.H */
