/*

 COLLISION_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\c_code\TileMapBuilder\gb_Tile Designer\tile_sets\basic_collisions.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define COLLISION_MAPWidth 20
#define COLLISION_MAPHeight 18
#define COLLISION_MAPBank 0

extern unsigned char COLLISION_MAP[];

/* End of COLLISION_MAP.H */
