// AUTOGENERATED FILE FROM png2mtspr
#define detective_16_Bank 200
#define detective_16_TILE_H 16
#define detective_16_WIDTH 16
#define detective_16_HEIGHT 16
#define detective_16_PIVOT_X 8
#define detective_16_PIVOT_Y 8

extern const UINT8 detective_16_data[544];
extern const metasprite_t* const detective_16_metasprites[12];
extern const metasprite_t* const detective_16_WALK[];
    extern const metasprite_t* const detective_16_UP[];
        extern const metasprite_t* const detective_16_DOWN[];