//AUTOGENERATED FILE FROM png2mtspr
#define detective_large_TILE_H 16
#define detective_large_WIDTH 24
#define detective_large_HEIGHT 32
#define detective_large_PIVOT_X 12
#define detective_large_PIVOT_Y 16

extern const UINT8 detective_large_data[2752];
extern const metasprite_t* const detective_large_metasprites[18];

extern const metasprite_t* const detective_walk_left[];
extern const metasprite_t* const detective_CROUCH[];
extern const metasprite_t* const detective_crawl_left[];
extern const metasprite_t* const detective_stand[];
extern const metasprite_t* const detective_JUMP[];
extern const metasprite_t* const detective_land[];
extern const metasprite_t* const detective_drop[];
extern const metasprite_t* const detective_LADDER[];
extern const metasprite_t* const detective_ONTOLADDER[];