// AUTOGENERATED FILE FROM png2mtspr
#define elevator_data_Bank 0
#define elevator_TILE_H 16
#define elevator_WIDTH 48
#define elevator_HEIGHT 16
#define elevator_PIVOT_X 24
#define elevator_PIVOT_Y 8

extern const UINT8 elevator_data[64];
extern const metasprite_t* const elevator_metasprites[1];
extern const metasprite_t* const elevator_frame[];