#include <gb/metasprites.h>

//AUTOGENERATED FILE FROM png2mtspr
#define enemy_arrow_TILE_H 16
#define enemy_arrow_WIDTH 16
#define enemy_arrow_HEIGHT 16
#define enemy_arrow_PIVOT_X 8
#define enemy_arrow_PIVOT_Y 8

extern const UINT8 enemy_arrow_data[192];
//extern const metasprite_t* const enemy_arrow_metasprites[3];

extern const metasprite_t* const enemy_arrow_left[];
extern const metasprite_t* const enemy_arrow_right[];