/*

 LEVEL_2_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 8
   Map size      : 100 x 18
   Tile set      : stage_drop_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level_2_map_h_INCLUDE
#define __level_2_map_h_INCLUDE

#define LEVEL_2_MAPWidth 100
#define LEVEL_2_MAPHeight 18
#define LEVEL_2_MAPBank 8

extern const void __bank_LEVEL_2_MAP;
extern const unsigned char LEVEL_2_MAP[];

#endif

/* End of LEVEL_2_MAP.H */
