/*

 LEVEL_2_COLLISION.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 7
   Map size      : 100 x 23
   Tile set      : stage_collision_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level_2_collision_h_INCLUDE
#define __level_2_collision_h_INCLUDE

#define LEVEL_2_COLLISIONWidth 100
#define LEVEL_2_COLLISIONHeight 23
#define LEVEL_2_COLLISIONBank 7

extern const void __bank_LEVEL_2_COLLISION;
extern const unsigned char LEVEL_2_COLLISION[];

#endif

/* End of LEVEL_2_COLLISION.H */
