/*

 LEVEL_1_COLLISION.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 5
   Map size      : 100 x 23
   Tile set      : stage_collision_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level_1_collision_h_INCLUDE
#define __level_1_collision_h_INCLUDE

#define LEVEL_1_COLLISIONWidth 100
#define LEVEL_1_COLLISIONHeight 23
#define LEVEL_1_COLLISIONBank 5

extern const void __bank_LEVEL_1_COLLISION;
extern const unsigned char LEVEL_1_COLLISION[];

#endif

/* End of LEVEL_1_COLLISION.H */
