/*

 LEVEL_1_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 6
   Map size      : 100 x 18
   Tile set      : stage_drop_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __level_1_map_h_INCLUDE
#define __level_1_map_h_INCLUDE

#define LEVEL_1_MAPWidth 100
#define LEVEL_1_MAPHeight 18
#define LEVEL_1_MAPBank 6

extern const void __bank_LEVEL_1_MAP;
extern const unsigned char LEVEL_1_MAP[];

#endif

/* End of LEVEL_1_MAP.H */
