/*

 LEVEL_TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __level_tileset_h_INCLUDE
#define __level_tileset_h_INCLUDE

/* Bank of tiles. */
#define LEVEL_TILESBank 4
/* Start of tile array. */
extern const void __bank_LEVEL_TILES;
extern const unsigned char LEVEL_TILES[];
#define LEVEL_TILESLen 13

#endif

/* End of LEVEL_TILESET.H */
