//AUTOGENERATED FILE FROM png2mtspr

#include <gb/gb.h>
#include <gb/metasprites.h>

const UINT8 NPC_electric_data[32] = {
0x00,0x00,0x00,0x00,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x3f,0x00,0x00,0x00,0x00
};

const metasprite_t NPC_electric_metasprite0[] = {
	{-8, -8, 0, 0}, {0, 8, 0, 32}, {metasprite_end}
};

const metasprite_t NPC_electric_metasprite1[] = {
	{-8, -8, 0, 0}, {0, 8, 0, 32}, {metasprite_end}
};

const metasprite_t* const NPC_electric_metasprites[2] = {
	NPC_electric_metasprite0, NPC_electric_metasprite1
};
const metasprite_t* const NPC_electric_animation[] = {
    NPC_electric_metasprite0, NPC_electric_metasprite1, NULL};