// AUTOGENERATED FILE FROM png2mtspr
#define NPC_electric_data_Bank 10
#define NPC_electric_TILE_H 16
#define NPC_electric_WIDTH 16
#define NPC_electric_HEIGHT 16
#define NPC_electric_PIVOT_X 8
#define NPC_electric_PIVOT_Y 8

extern const UINT8 NPC_electric_data[128];
extern const metasprite_t* const NPC_electric_metasprites[2];
extern const metasprite_t* const NPC_electric_animation[];