/*

 STAGE_DROP_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 100 x 18
   Tile set      : stage_drop_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define STAGE_DROP_MAPWidth 100
#define STAGE_DROP_MAPHeight 18
#define STAGE_DROP_MAPBank 6

extern const unsigned char STAGE_DROP_MAP[];

/* End of STAGE_DROP_MAP.H */
