/*

 STAGE_DROP_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Bank of tiles. */
#define STAGE_DROP_TILESBank 2
/* Start of tile array. */
extern unsigned char STAGE_DROP_TILES[];
#define STAGE_DROP_TILESLen 13

/* End of STAGE_DROP_TILES.H */
