/*

 STAGE_DROP_COLLISION.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 100 x 23
   Tile set      : stage_collision_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define STAGE_DROP_COLLISIONWidth 100
#define STAGE_DROP_COLLISIONHeight 23
#define STAGE_DROP_COLLISIONBank 6

extern unsigned char STAGE_DROP_COLLISION[];

/* End of STAGE_DROP_COLLISION.H */
