//AUTOGENERATED FILE FROM png2mtspr
#define vertical_platform_V1_TILE_H 16
#define vertical_platform_V1_WIDTH 48
#define vertical_platform_V1_HEIGHT 16
#define vertical_platform_V1_PIVOT_X 24
#define vertical_platform_V1_PIVOT_Y 8

extern const UINT8 vertical_platform_V1_data[64];
extern const metasprite_t* const vertical_platform_V1_metasprites[1];
extern const metasprite_t* const elevator_frame[];
