//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_vertical_platform_V1_H
#define METASPRITE_vertical_platform_V1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define vertical_platform_V1_TILE_H 16
#define vertical_platform_V1_WIDTH 48
#define vertical_platform_V1_HEIGHT 16
#define vertical_platform_V1_PIVOT_X 24
#define vertical_platform_V1_PIVOT_Y 8
#define vertical_platform_V1_PIVOT_W 48
#define vertical_platform_V1_PIVOT_H 16

BANKREF_EXTERN(vertical_platform_V1)

extern const uint16_t vertical_platform_V1_palettes[4];
extern const uint8_t vertical_platform_V1_tiles[64];

extern const metasprite_t* const vertical_platform_V1_metasprites[1];

#endif