/*

 WORLD1_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define WORLD1_TILESBank 10
/* Start of tile array. */
extern unsigned char WORLD1_TILES[];
#define WORLD1_TILESLen 4

/* End of WORLD1_TILES.H */
