/*

 WORLD1_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 36
   Tile set      : C:\c_code\projects\detective\detective_platformer_actors_physics\res\tiles\world1_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WORLD1_MAPWidth 40
#define WORLD1_MAPHeight 36
#define WORLD1_MAPBank 202

extern unsigned char WORLD1_MAP[];

/* End of WORLD1_MAP.H */
