/*
    SUBMAP_TILES.H
    Generated by gb_map_converter v1.2.
*/

#define SUBMAP_TILE_COUNT 238
#define SUBMAP_TILE_BANK 101

#define SUBMAP_PALETTE 0x1B

extern const unsigned char SUBMAP_TILE_DATA[];
