/*

 WORLD1_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 101
   Map size      : 40 x 36
   Tile set      : world1_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __world1_map_h_INCLUDE
#define __world1_map_h_INCLUDE

#define WORLD1_MAPWidth 40
#define WORLD1_MAPHeight 36
#define WORLD1_MAPBank 101

extern const void __bank_WORLD1_MAP;
extern const unsigned char WORLD1_MAP[];

#endif

/* End of WORLD1_MAP.H */
