/*

 WORLD1_COLLISION.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 36
   Tile set      : stage_collision_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WORLD1_COLLISIONWidth 40
#define WORLD1_COLLISIONHeight 36
#define WORLD1_COLLISIONBank 180

extern unsigned char WORLD1_COLLISION[];

/* End of WORLD1_COLLISION.H */
